#!/usr/bin/env sh

# This file is sourced when launching a DM from startx/xinit

# session launch

xss-lock -- slock &
redshift &
dunst -follow mouse &> /dev/null & #temp fix
# MPD daemon start (if no other user instance exists)
[ -z "$(pidof mpd)" ] && mpd
[ -z "$(pgrep -f sb-mpdup)" ] && sb-mpdup &
pulsemixer --set-volume 50
sbacklight set 3 &
setbg &
dwmblocks &
xrdb "$XDG_CONFIG_HOME/X11/xresources"

setxkbmap 'fr(oss)'
remaps &
sxhkd &
