#!/usr/bin/env sh

# This file is sourced when launching a DM from startx/xinit

# session launch

xss-lock -- slock &
redshift &
dunst &> /dev/null & #temp fix
# MPD daemon start (if no other user instance exists)
[ ! -s ~/.config/mpd/pid ] && mpd
[ -z "$(pgrep -f sb-mpdup)" ] && sb-mpdup &
pulsemixer --set-volume 50
setbg &
dwmblocks &
xrdb "$XDG_CONFIG_HOME/X11/xresources"
xrdb -merge "$XDG_STATE_HOME/xcolors"

setxkbmap 'fr(oss)'
xset r rate 300 50 &
sxhkd &
